[package]
name = "adventofcode-2021"
version = "0.1.0"
edition = "2021"
license="MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array_tool = "1.0.3"
indoc = "1.0.3"
itertools = "0.10.1"
lazy_static = "1.4.0"
regex = "1.5.4"